FROM gradle:8.7.0-jdk21-alpine AS build
COPY --chown=gradle:gradle . /home/gradle/src
WORKDIR /home/gradle/src
RUN gradle clean bootJar --no-daemon

FROM eclipse-temurin:21
EXPOSE 8080
RUN mkdir /app
COPY --from=build /home/gradle/src/build/libs/*.jar /app/tech-resume.jar
#RUN gradlew clean bootJar
#ADD build/libs/*.jar demo.jar
ENTRYPOINT ["java", "-jar", "/app/tech-resume.jar", "--spring.profiles.active=fly"]