FROM node:alpine AS builder

WORKDIR /app

COPY . /app

RUN npm install
RUN npm install -g @angular/cli
EXPOSE 3000
CMD ["ng", "serve", "--configuration", "fly", "--disable-host-check", "--port", "3000", "--host", "0.0.0.0"]
