spring:
  datasource:
    url: jdbc:postgresql://db:5432/resume
    username: postgres
    password: postgres


server:
  port: 8080

coop:
  stlma:
    tech:
      resume:
        update-token: "ChangeMe"
        allowedOrigins:
          - http://localhost:4201
          - http://localhost:4200


logging:
  level:
    coop:
      stlma:
        tech:
          resume: trace