spring:
  datasource:
    url: ${DB_URL}
    username: ${DB_USER}
    password: ${DB_PASS}
    driver-class-name: org.postgresql.Driver
  jpa:
    show-sql: true
  flyway:
    create-schemas: true
    locations: classpath:db/migration/common, classpath:db/migration/dml

server:
  port: 8080

logging:
  level:
    coop:
      stlma:
        tech:
          resume: trace