spring:
  jpa:
    show-sql: false
  datasource:
    url: ${DB_URL}
    driver-class-name: org.postgresql.Driver

server:
  port: 8080

coop:
  stlma:
    tech:
      resume:
        update-token: ${UPDATE_SECRET}
        allowedOrigins:
          - https://tech-resume-ui.fly.dev
          - https://tech-resume.citizenabacus.com